services:
  # golang
  web:
    container_name: ${APP_CONTAINER_NAME}
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./build/dockerfiles/golang/Dockerfile
    volumes: # マウント
      - ./web:/usr/local/go/src/app
      # - .env:/usr/local/go/src/app/web/.env
    tty: true # コンテナの永続化
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000
  # postgresql
  db:
    container_name: ${DB_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/dockerfiles/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      # - ./web/database/init:/docker-entrypoint-initdb.d # DBを初期化
    ports:
      - ${DB_PORT}:5432

volumes:
  db-store: